### ISSUE TITLE
error when running as github action

### ISSUE THREAD

**Issue by matthewmayer** [Logerfo/close-label#174]
```
src/index.ts:52:48 - error TS2339: Property 'issues' does not exist on type 'GitHubAPI'.

52             const issue = await context.github.issues.get(context.issue({
                                                  ~~~~~~

src/index.ts:55:57 - error TS7006: Parameter 'label' implicitly has an 'any' type.

55             const currentLabels = issue.data.labels.map(label => label.name)
                                                           ~~~~~

src/index.ts:81:34 - error TS2339: Property 'issues' does not exist on type 'GitHubAPI'.

81             await context.github.issues.addLabels(context.issue({
                                    ~~~~~~
```

**Comment by Logerfo** [comment]
What branch/tag/commit did you use as target?

**Comment by matthewmayer** [comment]
My whole YML looks like this

```
name: Close-label
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: logerfo/close-label@0.0.4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```
